// Sprites are rows of palette keys; "." is empty.
export const PALETTE: Record<string, string> = {
  k: "#0a0a0b",
  o: "#f97316",
  O: "#fdba74",
  b: "#0ea5e9",
  B: "#7dd3fc",
  w: "#fdf5dd",
  g: "#3f3f46",
  G: "#71717a",
  e: "#22c55e",
};

const head = (c: string, C: string) => [
  "....kk....",
  "...k" + C + C + "k...",
  "..k" + c + c + c + c + "k..",
  ".k" + c + c + c + c + c + c + "k.",
  "k" + c + "wwwwww" + c + "k",
  "k" + c + "wkwwkw" + c + "k",
  "k" + c + "wkwwkw" + c + "k",
  "k" + c + "wwwwww" + c + "k",
  ".k" + c + c + c + c + c + c + "k.",
  "..kkkkkk..",
];

export const SPRITES: Record<string, string[]> = {
  maya: head("o", "O"),
  theo: head("b", "B"),
  door: [
    "..kkkkkk..",
    "..kggggk..",
    "..kgGGgk..",
    "..kgGGgk..",
    "..kggggk..",
    "..kggook..",
    "..kggggk..",
    "..kgGGgk..",
    "..kggggk..",
    "kkkkkkkkkk",
  ],
  link: [
    "..........",
    "oooo......",
    "o..o......",
    "o..obbbb..",
    "o..ob..b..",
    "oooob..b..",
    "....b..b..",
    "....bbbb..",
    "..........",
    "..........",
  ],
  check: [
    "..........",
    ".........e",
    "........ee",
    ".......ee.",
    "e.....ee..",
    "ee...ee...",
    ".ee.ee....",
    "..eee.....",
    "...e......",
    "..........",
  ],
  replay: [
    "..........",
    "...G....G.",
    "..GG...GG.",
    ".GGG..GGG.",
    "GGGG.GGGG.",
    ".GGG..GGG.",
    "..GG...GG.",
    "...G....G.",
    "..........",
    "..........",
  ],
};
